pipeline{
    agent any
    tools{
        maven 3.9.7
    }
    stages{
       stage("Clean Up"){
         steps{
            deleteDir()
         }
       } 
       stage("Build"){
         steps{
            echo "Faza Build"
         }
       }
       stage("Deploy"){
         steps{
            echo "Faza Deploy"
         }
       }
       stage("Test"){
         steps{
            echo "Faza Test"
         }
       }
       stage("Release"){
         steps{
            echo "Faza Release"
         }
       }
    }
}
